# Generated by Django 3.1.3 on 2020-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=30)),
                ('date_blog', models.DateTimeField()),
                ('text_blog', models.CharField(max_length=300)),
                ('image_blog', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
